Develop
Schalure/gofermart pull request #1
Opened 2023-12-22 11:38 UTC by Schalure

2023-12-27 20:54 UTC, capsulated requested changes
Видно, что работа проделана большая, в общем проект хороший.

Замечания добавил. С какими-то комментариями ты может не согласишься - на эти комменты необходимо ответить и обосновать выбранный подход.

А можно и созвонится 1-1, пробежимся и синхронизируем понимание структуры программы и обсудим комментарии, это скорее всего, будет быстрее. Для этого пиши в директ пачки для согласования времени

2023-12-27 20:54 UTC, capsulated commented on docs/gofermart.drawio
Удобнее [mermaid](https://mermaid.js.org/) использовать прям в markdown, описательный язык для схематичных диаграмм, отлично рендерится на github/gitlab и в других сервисах

2023-12-27 20:54 UTC, capsulated commented on cmd/gophermart/main.go
> +	//	orderChecker := loyaltysystem.NewMockLoyaltySystem()
Не забывай удалять комментарии перед коммитом

2023-12-27 20:54 UTC, capsulated commented on cmd/gophermart/main.go
> +		config.AppConfig.LoginRules,
А можно же просто `AppConfig` передать целиком. Чем меньше входных параметров, тем лучше. Оптимально - это 1-2 параметра

2023-12-27 20:54 UTC, capsulated commented on internal/configs/appconfig.go
> +// Application configugation struct
Тогда сразу лучше [godoc](https://www.youtube.com/watch?v=80VT3xexcWs) лучше пиши, по нему доку можно сгенерить

2023-12-27 20:54 UTC, capsulated commented on internal/gofermart/gofermart.go
> +	//close(g.inputCh)
❌ Пустой метод

2023-12-27 20:54 UTC, capsulated commented on internal/gofermart/gofermaterrors/errors.go
> +package gofermaterrors
Лучше error'ы по уровням абстракций определить, то есть ошибки уровня базы данных (это psql ошибки, у них свой код есть), ошибки уровня http хендлеров (это статус коды), могут также быть ошибки записи/чтения файлов, ошибки определённых го-рутин.

По-хорошему, должна быть цепочка возвращаемых ошибок каждого уровня и трейс файлов и точке вызова. 

В нашем задании было бы отлично по уровням распределить, если успеешь

2023-12-27 20:54 UTC, capsulated commented on internal/gofermart/loyaltypoints.go
> +	user, err := g.storager.GetUserByLogin(ctx2, login)
❌  Должна быть транзакция, так как в одном методе несколько SQL вызовов

В идеале - это минимальное количество SQL запросов. Скажем, получение заказа можно выбрать с LEFT JOIN к таблице пользователей, и за счёт этого вместо двух запросов создаётся один. Но, также надо помнить о скорости и оптимальности запроса

2023-12-27 20:54 UTC, capsulated commented on internal/gofermart/orders.go
> +const RepetitiveCheckTime = time.Second * 2
⚠️ Лучше перенести в конфиг

2023-12-27 20:54 UTC, capsulated commented on internal/gofermart/orders.go
> +	if err == nil {
Лучше всегда [проверять существование ошибки и останавливать выполнение](https://go.dev/wiki/CodeReviewComments#indent-error-flow) (обрабатываем сначала ошибки, и если их нет - идём по "главному" сценарию метода и в самом конце метода возвращаем, если надо, успешный результат)

В данном случае, удобно доработать метод, чтобы возвращал, к примеру, дополнительный флаг существования order, или кейс `order == nil && err == nil` - отсутствия как заказа, так  и ошибок

2023-12-27 20:54 UTC, capsulated commented on internal/gofermart/orders.go
> +	orders, err := g.storager.GetOrdersToUpdateStatus(ctxGetOrders)
Если создать другой пакет, с к примеру `accrual` и в нём реализовать всю логику работы со сторонним сервисом бонусов, будет удобнее. А воркеру `Gofermart` передавать указатель на воркер `accrual` в конструкторе и пользоваться методами `accrual`'a. И в нём же запускать все рутины

2023-12-27 20:54 UTC, capsulated commented on internal/gofermart/orders.go
> +			g.loggerer.Debugw("closed pauseSignalCh")
Вот в этой части не помешали бы комментарии, а можно даже просто в логгер чуть подробнее написать, какой канал за что отвечает

2023-12-27 20:54 UTC, capsulated commented on internal/gofermart/users.go
> +	pc := "func (g *Gofermart) AuthenticationUser(ctx context.Context, login, password string) (string, error)"
В некоторых логгерах есть возможность настройки вывода имени метода и строки, в котором произошёл вызов. Я часть пользуюсь стандартным логгером go:
```go
package main

import (
	"log"
)

func main() {
	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)
	log.Println("Starting app...")
}
```

А подобные логи редактировать в случае изменений, скажем, сигнатуры метода, придётся редактировать и лог, так как DRY

2023-12-27 20:54 UTC, capsulated commented on internal/loyaltysystem/loyaltysystem.go
> +	queryString := host + "/api/orders/{" + orderNumberParName + "}"
Можно в константу/переменную вынести, как template для рендера адреса

2023-12-27 20:54 UTC, capsulated commented on internal/loyaltysystem/loyaltysystem.go
> +	switch res.Status {
Скорее мапу создать для этого. Или прям один-в-один значение статуса записывать, `orderStatus = res.Status`? Или enum

2023-12-27 20:54 UTC, capsulated commented on internal/loyaltysystem/loyaltysystem.go
> +	switch res.Status {
И `res` очень похоже на `resp`. Лучше `rslt` или что-от подобное

2023-12-27 20:54 UTC, capsulated commented on internal/server/server.go
> +
❌ Пустой метод

2023-12-27 20:54 UTC, capsulated commented on internal/storage/models.go
> +type Order struct {
Уже очень похоже, что нужно выносить модели в отдельные пакеты глобальные, так как они и в storage и handlers используются. Только выносить их надо также в несколько пакетов: `User`, `Order` и т.п., так как один глобальный пакет `model` будет в зависимостях всех сервисов/воркеров, что создаёт высокую "связанность" в коде

2023-12-27 20:54 UTC, capsulated commented on internal/server/midleware.go
> +func NewMidleware(logger gofermart.Loggerer, tokenCheker TokenCheker) *Middleware {
Общий объект с конструктором для Middleware скорее лишнее. Можно независимые функции, может даже несколько пакетов или подпакетов. Либо свой тип со своим конструктором для каждой из middleware. В текущем проекте, не критично, а в реальных проектах middlware'ей может быть много и варьируемое их использование

2023-12-27 20:54 UTC, capsulated commented on internal/server/handlerusers.go
> +func getAuthenticationData(r io.Reader) (authenticationData, error) {
Это лишнее, лучше прям в хендлере читать тело. При просмотре кода будет удобнее

2023-12-27 20:54 UTC, capsulated commented on internal/server/handlerusers.go
> +	ctx, cancel := context.WithTimeout(request.Context(), 5*time.Second)
5 секунд, как по мне, многовато)))

2023-12-27 20:54 UTC, capsulated commented on internal/server/handlerorders.go
> +	for i, order := range orders {
А почему преобразование `order`  в `orderInfo` прям в хендлере? Это всё же логика, как раз, для `orderManager`'а. Можно даже и в методе хранилки это преобразование делать. Либо типу orders добавить метод, который сам преобразовывает: `ordersInfo = orders.ToInfo()`. Но лучше не в хендлере

2023-12-27 20:54 UTC, capsulated commented on internal/server/handlerloyaltypoints.go
> +	type Withdrawal struct {
Новый тип прям в хендлере точно нужен? Может на уровне пакет с маленькой буквы объявить? Или преобразовывать где-то в менеджере или там, где объект первый раз появляется в коде

2023-12-27 20:54 UTC, capsulated commented on internal/server/handlerloyaltypoints.go
в имени файла handler можно убрать, а `loyalty_points.go` разделить подчёркиванием, а то очень сложно читать

2024-01-04 08:12 UTC, Schalure commented on cmd/gophermart/main.go
> +		config.AppConfig.LoginRules,
Я сначала так и сделал, но потом, когда тесты начали расти решил, что удобнее передавать сразу значения и не создавать лишний инстанс config

2024-01-04 08:21 UTC, Schalure commented on internal/configs/appconfig.go
> +// Application configugation struct
ок, учту. спасибо

2024-01-04 08:36 UTC, Schalure commented on internal/server/handlerloyaltypoints.go
В теории говорили, что имена файлов должны быть без подчеркиваний, чтобы отличать созданные файлы от сгенерированных?

2024-01-07 09:10 UTC, Schalure commented on internal/gofermart/loyaltypoints.go
> +	user, err := g.storager.GetUserByLogin(ctx2, login)
оптимизировал запрос:
1. Обновил таблицу - теперь бонусных баллов не может быть меньше нуля, теперь проверка идет на уровне БД (если пытаемся записать число меньше нуля, выдаст ошибку)
2. Оставил только одно обращение к БД

2024-01-07 09:57 UTC, Schalure commented on internal/gofermart/orders.go
> +	if err == nil {
Сделал проверку на уникальность нового ордера, и уже если что-то пошло не так делаю еще один запрос к бд, чтобы узнать что именно не так. раньше было наоборот

2024-01-08 16:36 UTC, Schalure commented on internal/server/handlerloyaltypoints.go
> +	type Withdrawal struct {
Используется только тут. Это сделано, чтобы разделить модели сервиса и модельки транспортной части

2024-01-08 16:39 UTC, Schalure commented on internal/server/handlerorders.go
> +	for i, order := range orders {
Это сделано, чтобы разделить модели сервиса и модели транспортной части.  `orderInfo` - это то что в запросе, а `order ` - это модели хранилки. Они никак не связаны. Метод сервиса возвращает модель хранилки, а хендлер уже берет только то, что ему надо для ответа

2024-01-08 16:40 UTC, Schalure commented on internal/server/handlerusers.go
> +	ctx, cancel := context.WithTimeout(request.Context(), 5*time.Second)
Учту, можно в следующих проектах это поправить? а то очень во многих местах встречается. А сколько обычно используют времени при обращении к БД?

2024-01-08 16:50 UTC, Schalure commented on internal/loyaltysystem/loyaltysystem.go
> +	switch res.Status {
один в один не получается:
acrual присылает:
        - `REGISTERED` — заказ зарегистрирован, но не начисление не рассчитано;
        - `INVALID` — заказ не принят к расчёту, и вознаграждение не будет начислено;
        - `PROCESSING` — расчёт начисления в процессе;
        - `PROCESSED` — расчёт начисления окончен;
а наш сервис оперирует:
        - `NEW` — заказ загружен в систему, но не попал в обработку;
        - `PROCESSING` — вознаграждение за заказ рассчитывается;
        - `INVALID` — система расчёта вознаграждений отказала в расчёте;
        - `PROCESSED` — данные по заказу проверены и информация о расчёте успешно получена.

2024-01-08 16:51 UTC, Schalure commented on internal/loyaltysystem/loyaltysystem.go
> +	queryString := host + "/api/orders/{" + orderNumberParName + "}"
Не понял как сделать  template

2024-01-08 16:52 UTC, Schalure commented on internal/gofermart/users.go
> +	pc := "func (g *Gofermart) AuthenticationUser(ctx context.Context, login, password string) (string, error)"
погуглю

2024-01-08 16:53 UTC, Schalure commented on internal/gofermart/orders.go
> +	orders, err := g.storager.GetOrdersToUpdateStatus(ctxGetOrders)
не хотелось бы разделять на два, так как придется двум инстансам давать доступ к базе данных

2024-03-26 09:46 UTC, merged